spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/invoice_ai
    username: invoice_ai
    password: invoice_ai

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8081